try { true.call(); } catch (e) {}
